service: freight-genie-slimphp-api

useDotenv: true

provider:
    name: aws
    region: us-east-1
    profile: dev
    memorySize: 256
    timeout: 15
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "elasticfilesystem:ClientMount"
              - "elasticfilesystem:ClientWrite"
          Resource: ${env:AP_ARN}
    vpc:
        securityGroupIds:
            - Ref: EfsSecurityGroup
        subnetIds:
            - ${env:SUBNET_ID}
    httpApi:
        cors:
            allowedOrigins:
                - "*"
            allowedHeaders:
                - "*"
            allowedMethods:
                - GET
                - POST
                - PUT
                - OPTIONS
                - DELETE

functions:
    web:
        handler: index.php
        runtime: php-83-fpm
        events:
            - httpApi: "*"
        fileSystemConfig:
            arn: ${env:AP_ARN}
            localMountPath: /mnt/efs

resources:
    Resources:
        EfsSecurityGroup:
            Type: AWS::EC2::SecurityGroup
            Properties:
                VpcId: ${env:VPC_ID}
                GroupDescription: "Security group for EFS mount target"
                SecurityGroupIngress:
                    - IpProtocol: tcp
                      FromPort: 2049
                      ToPort: 2049
                      CidrIp: 10.0.0.0/16

package:
    patterns: # Exclude files from deployment
        - "!node_modules/**"
        - "!tests/**"
        - "db/quotes-db.sqlite"

plugins:
    - ./vendor/bref/bref
