service: freight-genie-slimphp-api

useDotenv: true

provider:
    name: aws
    region: us-east-1
    profile: dev
    timeout: 30
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "elasticfilesystem:ClientMount"
              - "elasticfilesystem:ClientWrite"
          Resource: ${env:AP_ARN}
    vpc:
        securityGroupIds:
            - ${env:SECURITY_GROUP_ID}
        subnetIds:
            - ${env:SUBNET_ID}
    httpApi:
        cors:
            allowedOrigins:
                - "*"
            allowedHeaders:
                - "*"
            allowedMethods:
                - GET
                - POST
                - PUT
                - OPTIONS
                - DELETE

functions:
    web:
        handler: index.php
        runtime: php-83-fpm
        events:
            - httpApi: "*"
        fileSystemConfig:
            arn: ${env:AP_ARN}
            localMountPath: /mnt/efs

package:
    patterns: # Exclude files from deployment
        - "!node_modules/**"
        - "!tests/**"
        - "db/quotes-db.sqlite"

plugins:
    - ./vendor/bref/bref
